### ISSUE TITLE
Пишем свой маленький парсер!

### ISSUE THREAD

**Issue by murych** [lambdafrela/parser#11]
[Сайт](http://www.livelib.ru/books/top), на котором лежит топ-100 популярных книг (по версии сайта, естественно) . Задача - вынуть названия книг в файл `output.txt`.

1. Чтобы начать работу над дз тебе понадобятся модули [`requests`](http://docs.python-requests.org/en/master/
) и [`beautifulsoup4`](http://www.crummy.com/software/BeautifulSoup/bs4/doc/) (по ссылкам - документация для любопытных). Про модули вообще расскажем в следующий раз, а пока установи их, с помощью командной строки и программы `pip` (открывать Python пока не нужно!)  
    `pip install beautifulsoup4 requests`
2. Далее, сделай себе форк [репозитория с парсером](https://github.com/lambdafrela/parser) и склонируй на свой компьютер. Убедись, что находишься в ветке __master__
3. Основная часть парсера уже готова к использованию:

    1. импортируем модули
    ```python
    import requests
    from bs4 import BeautifulSoup
    ```
    2. задаем ссылку на сайт, который будем парсить
    ```python
    target_url = 'https://www.livelib.ru/books/top'
   	```
    3. отправляем запрос по ссылке, забирая исходный код страницы:
    ```python
    r = requests.get(target_url)
	r.encoding = 'utf-8'
    ```
    4. пихаем исходный код в СУП. интересующие нас названия фильмов лежат в тэге `<a class="tag-book-title with-cycle">`, эти тэги и будем искать
    ```python
    soup = BeautifulSoup(r.text,  "html.parser")
	top_titles = soup.find_all("a", class_="tag-book-title")
    ```
    5. теперь твой ход - открой на запись файл `output.txt` и запиши туда все названия книг
    ```python
    with open('output.txt','w',encoding='utf8') as f:
    	твой ход :)
    ```
4. Как закончишь - выкладывай свои изменения и делай Pull Request!

**Comment by iDevPro** [comment]
```
def getBooks(self, target_url):
        # request url
        r = requests.get(target_url)
        r.encoding = 'utf-8'

        # parse url
        soup = BeautifulSoup(r.text, "html.parser")

        # get list of books
        book_list = soup.find(id="booklist")

        return list(map(lambda book: getBookObject(book), book_list))

def getBookObject(book):
        bookObject = {}

        # brow-book-name provide (book link, book full title, book name)
        bookName = book.find(class_="brow-book-name")
        bookObject["link"] = bookName.get("href")
        bookObject["full_title"] = bookName.get("title")
        bookObject["title"] = bookName.getText()

        # brow-book-author provide (book title)
        bookTitle = book.find(class_="brow-book-author")
        bookObject["author"] = bookTitle.getText()

        # brow-genres provide (book genres [])
        bookGenres = book.find(class_="brow-genres").findChildren("a")
        bookObject["genres"] = list(map(lambda genre: genre.getText(), bookGenres))

        return bookObject
```

Беда в том что например мне надо достать Read/Wish списки, а там ReadMore ;(
